### ISSUE TITLE
Help for post api

### ISSUE THREAD

**Issue by princeasokan** [jimlowrey/aqua-sql#4]
Hi,
I'm using your project as sample demo, of my project. I tried to create the rest api in server folder. The get method is available to access from the ARC/web. But when I try to access the post method it giving me error 
{
"statusCode": 403,
"error": "Forbidden"
}.
Even i tried to run your project, that also not availble for outside project access for post api. I tried multiple option but no use. If you can help me tell me where thing restrictions metioned in your project.

**Comment by jimlowrey** [comment]
Not sure I follow.  

1) are you posting over TLS?

2) are you having success posting from the sample project?

**Comment by princeasokan** [comment]
thank you for your time, i got the solution. I just command the part of mannefest.js      
by refering 
https://github.com/jedireza/aqua/wiki/HTTP-403-forbidden-when-accessing-API-endpoints 
   {
            plugin: {
                register: 'crumb',
                options: {
                    restful: true
                }
            }
        },
thanks.

**Comment by jimlowrey** [comment]
great!
